
apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-generator-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-generator
            image: todo-generator:latest
            imagePullPolicy: Always
            env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-service:80/api/todos"
            - name: RANDOM_FACT_API_URL
              value: "http://numbersapi.com/random/trivia"
            resources:
              requests:
                cpu: "10m"
                memory: "32Mi"
              limits:
                cpu: "50m"
                memory: "64Mi"
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1