apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-ping-pong-pv
  labels:
    type: local-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/tmp/kube"
    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-ping-pong-pvc
  labels:
    app: shared-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  selector:
    matchLabels:
      type: local-storage
