apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-logs-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: log-output-config
      containers:
      - name: logger-container
        image: honganmaki/log-output-logger:latest
        imagePullPolicy: Always
        env:
        - name: LOG_FILE_DIR
          value: "/shared-logs"
        volumeMounts:
        - name: shared-logs-volume
          mountPath: /shared-logs
      - name: reader-container
        image: honganmaki/log-output-reader:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
        - name: LOG_FILE_DIR
          value: "/shared-logs"
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-config
              key: MESSAGE
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: shared-logs-volume
          mountPath: /shared-logs
        - name: config-volume
          mountPath: "/etc/config"
          readOnly: true

