apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-logs-volume
        emptyDir: {}
      - name: ping-pong-shared-data
        persistentVolumeClaim:
          claimName: shared-ping-pong-pvc
      containers:
      - name: logger-container
        image: honganmaki/log-output-logger:latest
        imagePullPolicy: Never
        env:
        - name: LOG_FILE_DIR
          value: "/shared-logs"
        volumeMounts:
        - name: shared-logs-volume
          mountPath: /shared-logs
      - name: reader-container
        image: honganmaki/log-output-reader:latest
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "3000"
        - name: LOG_FILE_DIR
          value: "/shared-logs"
        - name: PINGPONG_SHARED_VOLUME_PATH
          value: "/mnt/shared-data"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: shared-logs-volume
          mountPath: "/shared-logs"
        - name: ping-pong-shared-data
          mountPath: "/mnt/shared-data"
