# namespace-exercises.yaml (Ensure this namespace exists in GKE)
apiVersion: v1
kind: Namespace
metadata:
  name: exercises
---
# postgres-secret.yaml (PostgreSQL Credentials Secret)
# Ensure you have applied this secret with your base64 encoded password
# kubectl apply -f postgres-secret.yaml -n exercises
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: exercises
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # Base64 encoded "postgres"
  POSTGRES_PASSWORD: Q2VwdGVuOTEh # REPLACE WITH YOUR BASE64 ENCODED PASSWORD
---
# postgres-statefulset-service.yaml (PostgreSQL StatefulSet and Service)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: exercises
spec:
  serviceName: "postgres-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:16.2-alpine # Public image from Docker Hub
        ports:
        - containerPort: 5432
          name: postgres-port
        env:
        - name: POSTGRES_DB
          value: "pingpongdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres # ADDED: subPath to avoid initdb: directory exists but is not empty
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard # Changed to 'standard' for GKE (Google's default StorageClass)
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: exercises
  labels:
    app: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: postgres-port
  type: ClusterIP # Keep as ClusterIP, internal service
---
# ping-pong-deployment.yaml (Ping-pong Application Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-deployment
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong-container
        image: honganmaki/ping-pong:latest # UPDATED: Image from Docker Hub
        imagePullPolicy: Always # Always pull image from public registry
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: PG_HOST
          value: "postgres-db-service"
        - name: PG_DATABASE
          value: "pingpongdb"
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
---
# ping-pong-service.yaml (Ping-pong Application Service)
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
  namespace: exercises
  labels:
    app: ping-pong
spec:
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 80 # External port for LoadBalancer
    targetPort: 3001 # Container's listening port
  type: LoadBalancer # UPDATED: Changed to LoadBalancer to expose externally