apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
  labels:
    app: ping-pong
spec:
  selector:
    app: ping-pong
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
