apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: todo-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz
    port: 3002