apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend-container
        image: todo-backend:latest # Ensure your GitHub Action updates this tag on every push
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: TODO_PG_HOST
          value: "todo-postgres-db-service"
        - name: TODO_PG_DATABASE
          value: "tododb"
        - name: TODO_PG_PORT
          value: "5432"
        - name: TODO_PG_USER
          valueFrom:
            secretKeyRef:
              name: todo-postgres-credentials
              key: POSTGRES_USER
        - name: TODO_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-postgres-credentials
              key: POSTGRES_PASSWORD
        - name: TODO_MAX_LENGTH
          valueFrom:
            configMapKeyRef:
              name: project-config
              key: TODO_MAX_LENGTH
        - name: NATS_SERVER_URL # ADDED: NATS Server URL for the backend
          value: "nats://nats:4222" # Assumes NATS service named 'nats' on port 4222
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3