apiVersion: v1
kind: ResourceQuota
metadata:
  name: gcp-critical-pods
  namespace: istio-system
spec:
  hard:
    pods: "1000"
    requests.cpu: "10"
    requests.memory: 20Gi
    # Removed limits.cpu and limits.memory from this quota's scope for system-node-critical pods.
    # Istio's Ztunnel should have its own requests/limits defined in its manifest.
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
