apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ns
  - manifests/ns.yaml

  # Secrets and CM
  - todo-backend/manifests/secret.yaml
  - todo-app/manifests/configmap.yaml

  # Add the PVC and PV here
  - todo-app/manifests/images-pv.yaml

  # DB
  - todo-backend/manifests/postgre.yaml 
  - todo-backend/manifests/service.yaml 
                                       
  # App
  - todo-backend/manifests/deployment.yaml 
  - todo-app/manifests/service.yaml
  - todo-app/manifests/deployment.yaml

  # Ingress/Gateway
  - todo-app/manifests/ingress.yaml

  # CronJobs/Jobs
  - todo-generator/manifests/cronjob.yaml
