apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/manifests/secret.yaml
- todo-app/manifests/configmap.yaml
- todo-app/manifests/images-pv.yaml
- todo-backend/manifests/postgre.yaml
- todo-backend/manifests/service.yaml
- todo-backend/manifests/backend-config.yaml
- todo-backend/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/ingress.yaml
- todo-backend/manifests/cronjob.yaml
- todo-generator/manifests/cronjob.yaml

images:
 
  - name: todo-backend
 
    newName: europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/todo-backend
    newTag: latest

  - name: todo-app
    newName: europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/todo-app
    newTag: latest

  - name: todo-generator
    newName: europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/todo-generator
    newTag: latest

  - name: db-backup-tool
    newName: europe-north1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/db-backup-tool
    newTag: latest