apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/manifests/secret.yaml
- todo-app/manifests/configmap.yaml
- todo-app/manifests/images-pv.yaml
- todo-backend/manifests/postgre.yaml
- todo-backend/manifests/service.yaml
- todo-backend/manifests/backend-config.yaml
- todo-backend/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/ingress.yaml
- todo-backend/manifests/cronjob.yaml
- todo-generator/manifests/cronjob.yaml
    # The backupsecret.yaml was removed in a previous step to fix ArgoCD sync issues.
    # - todo-backend/manifests/backupsecret.yaml