apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


  # Secrets and CM

  # Persistent Volume Claim for todo-app

  # DB

  # App

  # Ingress/Gateway

  # CronJobs/Jobs
resources:
- todo-backend/manifests/secret.yaml
- todo-app/manifests/configmap.yaml
- todo-app/manifests/images-pv.yaml
- todo-backend/manifests/postgre.yaml
- todo-backend/manifests/service.yaml
- todo-backend/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/ingress.yaml
- todo-generator/manifests/cronjob.yaml
namespace: 2-redeploy
