apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dummysites.stable.dwk
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.dwk
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        # schema used for validation, pruning, and defaulting
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
              required:
              - website_url
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                url:
                  type: string
      # Enable the status subresource
      subresources:
        status: {}
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    plural: dummysites
    singular: dummysite
    kind: DummySite