apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller-sa
  namespace: default # Or the namespace where you deploy the controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller-role
rules:
- apiGroups: ["stable.dwk"]
  resources: ["dummysites"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["stable.dwk"]
  resources: ["dummysites/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["stable.dwk"]
  resources: ["dummysites/finalizers"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-controller-binding
subjects:
- kind: ServiceAccount
  name: dummysite-controller-sa
  namespace: default # Must match the ServiceAccount's namespace
roleRef:
  kind: ClusterRole
  name: dummysite-controller-role
  apiGroup: rbac.authorization.k8s.io