apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  namespace: project
  labels:
    app: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP