name: Release application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  ARTIFACT_REGISTRY_LOCATION: europe-north1
  ARTIFACT_REGISTRY_REPO: honganmakirepo
  TODO_BACKEND_IMAGE_NAME: todo-backend
  TODO_BACKEND_DOCKERFILE_PATH: project-in-cloud/todo-backend/
  TODO_APP_IMAGE_NAME: todo-app
  TODO_APP_DOCKERFILE_PATH: project-in-cloud/todo-app/
  TODO_GENERATOR_IMAGE_NAME: todo-generator
  TODO_GENERATOR_DOCKERFILE_PATH: project-in-cloud/todo-generator/

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Form todo-backend image tag
        run: echo "TODO_BACKEND_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.TODO_BACKEND_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build todo-backend Docker Image
        run: docker build --tag ${{ env.TODO_BACKEND_FULL_IMAGE_TAG }} ${{ env.TODO_BACKEND_DOCKERFILE_PATH }}

      - name: Publish todo-backend Docker Image
        run: docker push ${{ env.TODO_BACKEND_FULL_IMAGE_TAG }}

      - name: Form todo-app image tag
        run: echo "TODO_APP_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.TODO_APP_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build todo-app Docker Image
        run: docker build --tag ${{ env.TODO_APP_FULL_IMAGE_TAG }} ${{ env.TODO_APP_DOCKERFILE_PATH }}

      - name: Publish todo-app Docker Image
        run: docker push ${{ env.TODO_APP_FULL_IMAGE_TAG }}

      - name: Form todo-generator image tag
        run: echo "TODO_GENERATOR_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.TODO_GENERATOR_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build todo-generator Docker Image
        run: docker build --tag ${{ env.TODO_GENERATOR_FULL_IMAGE_TAG }} ${{ env.TODO_GENERATOR_DOCKERFILE_PATH }}

      - name: Publish todo-generator Docker Image
        run: docker push ${{ env.TODO_GENERATOR_FULL_IMAGE_TAG }}

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Update Kustomization image tags and Deploy
        working-directory: project-in-cloud/
        run: |
          kustomize edit set image ${{ env.TODO_BACKEND_IMAGE_NAME }}=${{ env.TODO_BACKEND_FULL_IMAGE_TAG }}
          kustomize edit set image ${{ env.TODO_APP_IMAGE_NAME }}=${{ env.TODO_APP_FULL_IMAGE_TAG }}
          kustomize edit set image ${{ env.TODO_GENERATOR_IMAGE_NAME }}=${{ env.TODO_GENERATOR_FULL_IMAGE_TAG }}

          kustomize build . | kubectl apply -f -

          echo "Sleeping for 10 seconds to allow the API server to register the new resources..."
          sleep 10s

          echo "Waiting for todo-backend deployment to roll out..."
          kubectl rollout status deployment/todo-backend-deployment -n project --timeout=5m
          echo "Waiting for todo-app deployment to roll out..."
          kubectl rollout status deployment/todo-app-deployment -n project --timeout=5m
          echo "Waiting for todo-generator deployment to roll out..."
          kubectl rollout status deployment/todo-generator-deployment -n project --timeout=5m

          echo "Service information:"
          kubectl get services -o 
