name: Release application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  ARTIFACT_REGISTRY_LOCATION: europe-north1
  ARTIFACT_REGISTRY_REPO: honganmakirepo
  TODO_BACKEND_IMAGE_NAME: todo-backend
  TODO_BACKEND_DOCKERFILE_PATH: project-in-cloud/todo-backend/
  TODO_APP_IMAGE_NAME: todo-app
  TODO_APP_DOCKERFILE_PATH: project-in-cloud/todo-app/
  TODO_GENERATOR_IMAGE_NAME: todo-generator
  TODO_GENERATOR_DOCKERFILE_PATH: project-in-cloud/todo-generator/
  DB_BACKUP_IMAGE_NAME: db-backup-tool
  DB_BACKUP_DOCKERFILE_PATH: project-in-cloud/db-backup-image/
  # ADDED: Broadcaster image details
  BROADCASTER_IMAGE_NAME: broadcaster
  BROADCASTER_DOCKERFILE_PATH: project-in-cloud/broadcaster/ # Ensure this path is correct

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Kubernetes Namespace
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "K8S_NAMESPACE=project" >> $GITHUB_ENV
          else
            SAFE_REF_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
            echo "K8S_NAMESPACE=$SAFE_REF_NAME" >> $GITHUB_ENV
          fi

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build and Publish todo-backend Docker Image
        run: |
          TODO_BACKEND_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.TODO_BACKEND_IMAGE_NAME }}:${{ github.sha }}
          docker build --tag $TODO_BACKEND_FULL_IMAGE_TAG ${{ env.TODO_BACKEND_DOCKERFILE_PATH }}
          docker push $TODO_BACKEND_FULL_IMAGE_TAG
          echo "TODO_BACKEND_FULL_IMAGE_TAG=$TODO_BACKEND_FULL_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Publish todo-app Docker Image
        run: |
          TODO_APP_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.TODO_APP_IMAGE_NAME }}:${{ github.sha }}
          docker build --tag $TODO_APP_FULL_IMAGE_TAG ${{ env.TODO_APP_DOCKERFILE_PATH }}
          docker push $TODO_APP_FULL_IMAGE_TAG
          echo "TODO_APP_FULL_IMAGE_TAG=$TODO_APP_FULL_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Publish todo-generator Docker Image
        run: |
          TODO_GENERATOR_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.TODO_GENERATOR_IMAGE_NAME }}:${{ github.sha }}
          docker build --tag $TODO_GENERATOR_FULL_IMAGE_TAG ${{ env.TODO_GENERATOR_DOCKERFILE_PATH }}
          docker push $TODO_GENERATOR_FULL_IMAGE_TAG
          echo "TODO_GENERATOR_FULL_IMAGE_TAG=$TODO_GENERATOR_FULL_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Publish DB Backup Docker Image
        run: |
          DB_BACKUP_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.DB_BACKUP_IMAGE_NAME }}:${{ github.sha }}
          docker build --tag $DB_BACKUP_FULL_IMAGE_TAG ${{ env.DB_BACKUP_DOCKERFILE_PATH }}
          docker push $DB_BACKUP_FULL_IMAGE_TAG
          echo "DB_BACKUP_FULL_IMAGE_TAG=$DB_BACKUP_FULL_IMAGE_TAG" >> $GITHUB_ENV

      # ADDED: Build and Publish Broadcaster Docker Image
      - name: Build and Publish Broadcaster Docker Image
        run: |
          BROADCASTER_FULL_IMAGE_TAG=${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.BROADCASTER_IMAGE_NAME }}:${{ github.sha }}
          docker build --tag $BROADCASTER_FULL_IMAGE_TAG ${{ env.BROADCASTER_DOCKERFILE_PATH }}
          docker push $BROADCASTER_FULL_IMAGE_TAG
          echo "BROADCASTER_FULL_IMAGE_TAG=$BROADCASTER_FULL_IMAGE_TAG" >> $GITHUB_ENV

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Create Namespace if it doesn't exist (for dynamic app components)
        run: kubectl create namespace ${{ env.K8S_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        continue-on-error: true

      # ADDED: Ensure 'prometheus' namespace exists for broadcaster
      - name: Create 'prometheus' Namespace if it doesn't exist
        run: kubectl create namespace prometheus --dry-run=client -o yaml | kubectl apply -f -
        continue-on-error: true

      - name: Inject GCS Service Account Key
        working-directory: project-in-cloud/
        run: |
          ENCODED_KEY=$(echo '${{ secrets.GCS_BACKUP_SERVICE_ACCOUNT_JSON }}' | base64 -w 0)
          sed -i "s|GCS_SA_KEY_PLACEHOLDER|$ENCODED_KEY|" todo-backend/manifests/backupsecret.yaml
        env:
          GCS_BACKUP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCS_BACKUP_SERVICE_ACCOUNT_JSON }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Update Kustomization image tags and Deploy dynamic app components
        working-directory: project-in-cloud/
        run: |
          # Apply namespace to all resources in this kustomization
          kustomize edit set namespace ${{ env.K8S_NAMESPACE }}
          kustomize edit set image ${{ env.TODO_BACKEND_IMAGE_NAME }}=${{ env.TODO_BACKEND_FULL_IMAGE_TAG }}
          kustomize edit set image ${{ env.TODO_APP_IMAGE_NAME }}=${{ env.TODO_APP_FULL_IMAGE_TAG }}
          kustomize edit set image ${{ env.TODO_GENERATOR_IMAGE_NAME }}=${{ env.TODO_GENERATOR_FULL_IMAGE_TAG }}
          kustomize edit set image ${{ env.DB_BACKUP_IMAGE_NAME }}=${{ env.DB_BACKUP_FULL_IMAGE_TAG }}

          # Build and apply to the dynamic namespace
          kustomize build . | kubectl apply -n ${{ env.K8S_NAMESPACE }} -f -

          echo "Sleeping for 10 seconds to allow the API server to register the new resources..."
          sleep 10s

          echo "Waiting for todo-backend deployment to roll out..."
          kubectl rollout status deployment/todo-backend-deployment -n ${{ env.K8S_NAMESPACE }} --timeout=5m
          echo "Waiting for todo-app deployment to roll out..."
          kubectl rollout status deployment/todo-app-deployment -n ${{ env.K8S_NAMESPACE }} --timeout=5m

          # Explicitly set the image for the todo-app deployment to force an update
          echo "Ensuring todo-app deployment uses the latest image tag..."
          kubectl set image deployment/todo-app-deployment todo-app-container=${{ env.TODO_APP_FULL_IMAGE_TAG }} -n ${{ env.K8S_NAMESPACE }}

          echo "Waiting for todo-app deployment to roll out after explicit image set..."
          kubectl rollout status deployment/todo-app-deployment -n ${{ env.K8S_NAMESPACE }} --timeout=5m

      # ADDED: Deploy Broadcaster and its Secret to 'prometheus' namespace
      - name: Deploy Broadcaster to 'prometheus' namespace
        working-directory: project-in-cloud/broadcaster/manifests/ # Assuming broadcaster manifests are here
        run: |
          # Create a temporary kustomization for the broadcaster to set its image tag
          # This avoids interfering with the main kustomization's namespace setting
          mkdir -p .kustomize_broadcaster_temp
          cp broadcaster-deployment.yaml .kustomize_broadcaster_temp/
          cp broadcaster-secrets.yaml .kustomize_broadcaster_temp/ # Copy the secret too

          echo "apiVersion: kustomize.config.k8s.io/v1beta1" > .kustomize_broadcaster_temp/kustomization.yaml
          echo "kind: Kustomization" >> .kustomize_broadcaster_temp/kustomization.yaml
          echo "resources:" >> .kustomize_broadcaster_temp/kustomization.yaml
          echo "  - broadcaster-deployment.yaml" >> .kustomize_broadcaster_temp/kustomization.yaml
          echo "  - broadcaster-secrets.yaml" >> .kustomize_broadcaster_temp/kustomization.yaml
          echo "images:" >> .kustomize_broadcaster_temp/kustomization.yaml
          # CORRECTED LINE: The 'name' should be the full image path without the tag
          echo "  - name: ${{ env.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.BROADCASTER_IMAGE_NAME }}" >> .kustomize_broadcaster_temp/kustomization.yaml
          # CORRECTED LINE: The 'newTag' should be just the Git SHA
          echo "    newTag: ${{ github.sha }}" >> .kustomize_broadcaster_temp/kustomization.yaml

          # Build and apply to the 'prometheus' namespace
          kustomize build .kustomize_broadcaster_temp/ | kubectl apply -n prometheus -f -

          echo "Sleeping for 5 seconds to allow the API server to register broadcaster resources..."
          sleep 5s
          echo "Waiting for broadcaster deployment to roll out..."
          kubectl rollout status deployment/broadcaster-deployment -n prometheus --timeout=5m

      - name: Get service information to confirm external access
        run: kubectl get services -n ${{ env.K8S_NAMESPACE }} -o wide
        # ADDED: Get broadcaster service info
      - name: Get broadcaster service information
        run: kubectl get services,deployments,pods -n prometheus -l app=broadcaster -o wide