apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  # ...
  template:
    # ...
    spec:
      containers:
      - name: todo-app-container
        # ...
        readinessProbe:
          httpGet:
            path: /
            port: 80
            host: todo-backend-service
          initialDelaySeconds: 30 # Increased from 15
          periodSeconds: 5
          timeoutSeconds: 5   # Increased from 3
          failureThreshold: 3