
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: project 
  name: cached-images-pv
  labels:
    type: image-cache-storage
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: "/tmp/kube-images"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: cached-images-pvc
  labels:
    app: image-cache-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
